
# define wikiOutDir or wikiPackageName
wikiPackageName = "github.com/com314159/godoc_to_markdown_wiki/example/wiki"

wikiOutDir = ""

[pages]
    [pages.user]
    apifiles = ["github.com/com314159/godoc_to_markdown_wiki/example/user/user.go","github.com/com314159/godoc_to_markdown_wiki/example/user/message/message.go"]
    # array type
    funcnames = ["GetUserInfo","ModifyUserInfo","DeleteUserMessage"]

    [pages.login]
    apifiles = ["github.com/com314159/godoc_to_markdown_wiki/example/login/login.go"]
    funcnames = ["Login"]
